# Generated by Django 5.2.7 on 2025-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatriotNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
                ('main_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Главное изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='Дополнительные изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость патриотического воспитания',
                'verbose_name_plural': 'Новости патриотического воспитания',
                'ordering': ['-date'],
            },
        ),
    ]
