# Generated by Django 4.2.7 on 2025-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiwayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('alt_text', models.TextField(blank=True, verbose_name='Alt текст')),
                ('original_src', models.URLField(max_length=1000, verbose_name='Original SRC')),
                ('data_src', models.URLField(blank=True, max_length=1000, verbose_name='Data SRC')),
                ('image_url', models.URLField(max_length=1000, verbose_name='URL изображения')),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='wikiway_images/', verbose_name='Локальное изображение')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('style_width', models.CharField(blank=True, max_length=50, verbose_name='Ширина в стиле')),
                ('style_height', models.CharField(blank=True, max_length=50, verbose_name='Высота в стиле')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Парсинг завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение Wikiway',
                'verbose_name_plural': 'Изображения Wikiway',
                'ordering': ['-created_at'],
            },
        ),
    ]
