# Generated by Django 4.2.7 on 2025-10-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wikiwayimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiwayimage',
            name='local_image',
        ),
    ]
