# Generated by Django 4.2.7 on 2025-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_wikiwayimage_local_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_cover',
            field=models.ImageField(blank=True, null=True, upload_to='posts/audio_covers/', verbose_name='Обложка аудио'),
        ),
    ]
