# Generated by Django 4.2.7 on 2025-10-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название региона/города')),
                ('description', models.TextField(verbose_name='Описание')),
                ('stories', models.TextField(help_text='Разделяйте истории точкой с запятой', verbose_name='Интересные истории')),
                ('coordinates', models.JSONField(help_text='JSON с координатами для отрисовки на карте', verbose_name='Координаты полигона')),
                ('center_lat', models.FloatField(verbose_name='Центральная широта')),
                ('center_lng', models.FloatField(verbose_name='Центральная долгота')),
                ('period', models.CharField(choices=[('ancient', 'Древность (до X века)'), ('middle_ages', 'Средневековье (X-XV века)'), ('grand_duchy', 'Великое Княжество Литовское (XIII-XVI века)'), ('polish_lithuanian', 'Речь Посполитая (XVI-XVIII века)'), ('russian_empire', 'В составе Российской империи (XVIII-XX века)'), ('soviet', 'Советский период (1917-1991)'), ('modern', 'Современная Беларусь (с 1991)')], max_length=20, verbose_name='Исторический период')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год события')),
                ('category', models.CharField(choices=[('war', 'Военные подвиги'), ('science', 'Наука и изобретения'), ('culture', 'Культура и искусство'), ('people', 'Выдающиеся личности'), ('mystery', 'Загадки и тайны')], max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='historical_regions/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Исторический регион',
                'verbose_name_plural': 'Исторические регионы',
                'db_table': 'app_historical_regions',
                'ordering': ['period', 'year'],
            },
        ),
    ]
