# Generated by Django 4.2.7 on 2025-10-17 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_historicalregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diamonds',
            field=models.IntegerField(default=0, verbose_name='Алмазы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(max_length=100, verbose_name='Тип задания')),
                ('difficulty', models.CharField(max_length=20, verbose_name='Сложность')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('diamonds_earned', models.IntegerField(default=0, verbose_name='Заработано алмазов')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
