# Generated by Django 4.2.7 on 2025-10-17 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_userprofile_diamonds_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('avatar_frame', 'Рамка аватарки'), ('profile_background', 'Фон профиля'), ('badge', 'Значок'), ('title', 'Особый титул'), ('animation', 'Анимация')], max_length=50, verbose_name='Категория')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], max_length=20, verbose_name='Редкость')),
                ('price', models.IntegerField(verbose_name='Цена в алмазах')),
                ('image', models.ImageField(upload_to='shop/items/', verbose_name='Изображение товара')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='shop/previews/', verbose_name='Превью')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='CSS класс для стилизации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазина',
                'ordering': ['category', 'price'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_avatar_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_avatar_frames', to='app.shopitem', verbose_name='Активная рамка аватарки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_badges', to='app.shopitem', verbose_name='Активный значок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_profile_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_backgrounds', to='app.shopitem', verbose_name='Активный фон профиля'),
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Надето')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвентарь пользователя',
                'verbose_name_plural': 'Инвентари пользователей',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
