# Generated by Django 4.2.7 on 2025-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shopitem_userprofile_active_avatar_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/items/', verbose_name='Изображение товара'),
        ),
    ]
